In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__

'1.1.0'

In [3]:
a_val = np.arange(24).reshape(2, 3, 4)
a_val

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [4]:
a_val[[0, 0], [1, 0] ]

array([[4, 5, 6, 7],
       [0, 1, 2, 3]])

In [5]:
a = tf.Variable(a_val, name = "a")

In [6]:
sess = tf.InteractiveSession()

In [7]:
sess.run(tf.global_variables_initializer())

In [8]:
sess.run(a[[0, 0], [1, 0] ])

TypeError: can only concatenate list (not "int") to list

In [9]:
sess.run(
    tf.gather_nd(a, indices = [[0, 0], [1, 0], [0,0] ])
)

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15],
       [ 0,  1,  2,  3]])