In [1]:
import numpy as np
import matplotlib.pyplot as pl

%matplotlib inline

In [2]:
import tensorflow as tf

In [3]:
v = tf.Variable([1, 2, 3])
w = tf.Variable([4, 5, 6])

In [8]:
expl = tf.stack([v, w, tf.ones_like(v)], name="expl", axis = 1)

In [21]:
expl.get_shape()

TensorShape([Dimension(3), Dimension(3)])

In [11]:
sess = tf.InteractiveSession()

In [15]:
sess.run(tf.global_variables_initializer())
print(sess.run(expl))

[[1 4 1]
 [2 5 1]
 [3 6 1]]


Try with scalar variables

In [13]:
sess.run(v[:, None])

array([[1],
       [2],
       [3]])

In [14]:
x = tf.Variable(1.0)
y = tf.Variable(2.0)

In [17]:
sess.run(tf.stack([x, y, 1])[None, :])

array([[ 1.,  2.,  1.]], dtype=float32)

In [20]:
sess.run(tf.concat([v, [1]], axis=0))

array([1, 2, 3, 1])