In [25]:
import tensorflow as tf

import numpy as np
import numpy.linalg as la

import pylab as pl
%pylab inline

import pandas as pd
from pandas import Series, DataFrame

Populating the interactive namespace from numpy and matplotlib


In [5]:
elems = np.array([1, 2, 3, 4, 5, 6])
tf_sum = tf.scan(lambda a, x: a + x, elems)

In [8]:
sess = tf.InteractiveSession()

In [9]:
sess.run(tf_sum)

array([ 1,  3,  6, 10, 15, 21])

# polynomial of matrix evaluated on vector

<tf.Variable 'weights:0' shape=(3,) dtype=float32_ref>

In [12]:
M = tf.Variable(np.diag([2, 3]), name = "M", dtype = np.float32)

In [14]:
v0 = tf.Variable([[2], [3]], name = "v0", dtype = np.float32)

In [15]:
weights = tf.Variable([1, 0, 1], name = "weights", dtype = np.float32)

In [21]:
Mn_v0 = tf.scan(
    fn = lambda vt, w: tf.matmul(M, vt),
    initializer = v0,
    elems = weights,
)

In [29]:
evol1 = tf.matmul(
    tf.stack([weights]),
    tf.reshape(Mn_v0, Mn_v0.shape[:-1])
)

In [18]:
sess.run(tf.global_variables_initializer())

In [30]:
sess.run(Mn_v0)

array([[[  4.],
        [  9.]],

       [[  8.],
        [ 27.]],

       [[ 16.],
        [ 81.]]], dtype=float32)

In [31]:
sess.run(evol1)

array([[ 20.,  90.]], dtype=float32)

In [33]:
Mn_v0_last = tf.foldl(
    fn = lambda v, w: tf.matmul(M, v),
    initializer = v0,
    elems = weights,
)

In [34]:
sess.run(Mn_v0_last)

array([[ 16.],
       [ 81.]], dtype=float32)

In [44]:
evol = tf.scan(
    fn = lambda v, w: (tf.matmul(M, v[0]), v[1] +  w * v[0] ),
    initializer = (v0, tf.zeros_like(v0)),
    elems = weights,
)

In [52]:
sess.run(evol)

(array([[[  4.],
         [  9.]],
 
        [[  8.],
         [ 27.]],
 
        [[ 16.],
         [ 81.]]], dtype=float32), array([[[  2.],
         [  3.]],
 
        [[  2.],
         [  3.]],
 
        [[ 10.],
         [ 30.]]], dtype=float32))

To my great dismay, replacing `scan` with `foldl` does not work:

In [53]:
evol = tf.foldl(
    fn = lambda v, w: (tf.matmul(M, v[0]), v[1] +  w * v[0] ),
    initializer = (v0, tf.zeros_like(v0)),
    elems = weights,
)

ValueError: The two structures don't have the same number of elements. First structure: [<tf.Tensor 'foldl_7/while/Identity:0' shape=() dtype=int32>, <tf.Tensor 'foldl_7/while/Identity_1:0' shape=(2, 2, 1) dtype=float32>], second structure: [<tf.Tensor 'foldl_7/while/add_1:0' shape=() dtype=int32>, [<tf.Tensor 'foldl_7/while/MatMul:0' shape=(2, 1) dtype=float32>, <tf.Tensor 'foldl_7/while/add:0' shape=(2, 1) dtype=float32>]].

In [46]:
power = tf.foldl(
    fn = lambda v, w: tf.matmul(M, v),
    initializer = v0,
    elems = weights,
)

In [47]:
sess.run(power)

array([[ 16.],
       [ 81.]], dtype=float32)

## Cycle through a dimension of length unknown in advance

In [1]:
import tensorflow as tf

In [2]:
a = tf.Variable([1, 2, 3], validate_shape=False)
b = tf.Variable([-1, 1, -1], validate_shape=False)

a.set_shape([None])
b.set_shape([None])

In [3]:
sess = tf.InteractiveSession()

In [4]:
sess.run(tf.global_variables_initializer())

In [5]:
sess.run([a, b])

[array([1, 2, 3]), array([-1,  1, -1])]

In [6]:
cyc = tf.map_fn(
    fn = lambda x: x[0] * x[1], 
    elems = (a, b),
    dtype = tf.int32
)

In [7]:
sess.run(cyc)

array([-1,  2, -3])

In [9]:
sess.run(cyc, {a: [1, 2, 3, 4], b : [-1, 1, -1, 1]})

array([-1,  2, -3,  4])

In [12]:
sess.run(cyc, {a: [1, 2, 3, 4], b : [-1, 1, -1, 1]})

array([-1,  2, -3,  4])

##### It seems however that broadcasting does not work

In [13]:
X = tf.Variable([[1, 2, 3], [4, 5, 6]], validate_shape=False)
X.set_shape([None, 3])

y = tf.Variable([-1, 1, -1])

In [14]:
sess.run(tf.global_variables_initializer())

In [19]:
cyc2 = tf.map_fn(
    fn = lambda x: x[0] * x[1], 
    elems = (X, y[None, :]),
    dtype = tf.int32
)

In [20]:
sess.run(cyc2, {X : [[1, 2, 3]]})

array([[-1,  2, -3]])

In [21]:
sess.run(cyc2)

InvalidArgumentError: TensorArray map_2/TensorArray_1_22: Could not read from TensorArray index 1 because it has not yet been written to.
	 [[Node: map_2/while/TensorArrayReadV3_1 = TensorArrayReadV3[dtype=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](map_2/while/TensorArrayReadV3_1/Enter, map_2/while/Identity, map_2/while/TensorArrayReadV3_1/Enter_1)]]

Caused by op 'map_2/while/TensorArrayReadV3_1', defined at:
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\ipykernel\__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\ipykernel\kernelapp.py", line 474, in start
    ioloop.IOLoop.instance().start()
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\zmq\eventloop\ioloop.py", line 162, in start
    super(ZMQIOLoop, self).start()
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\tornado\ioloop.py", line 887, in start
    handler_func(fd_obj, events)
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\tornado\stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\zmq\eventloop\zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\zmq\eventloop\zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\zmq\eventloop\zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\tornado\stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\ipykernel\kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\ipykernel\kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\ipykernel\kernelbase.py", line 390, in execute_request
    user_expressions, allow_stdin)
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\ipykernel\ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\ipykernel\zmqshell.py", line 501, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\IPython\core\interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\IPython\core\interactiveshell.py", line 2821, in run_ast_nodes
    if self.run_code(code, result):
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-19-dd88dc595acc>", line 4, in <module>
    dtype = tf.int32
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\tensorflow\python\ops\functional_ops.py", line 389, in map_fn
    swap_memory=swap_memory)
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2770, in while_loop
    result = context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2599, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2549, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\tensorflow\python\ops\functional_ops.py", line 378, in compute
    packed_values = input_pack([elem_ta.read(i) for elem_ta in elems_ta])
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\tensorflow\python\ops\functional_ops.py", line 378, in <listcomp>
    packed_values = input_pack([elem_ta.read(i) for elem_ta in elems_ta])
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\tensorflow\python\util\tf_should_use.py", line 88, in fn
    return method(self, *args, **kwargs)
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\tensorflow\python\ops\tensor_array_ops.py", line 280, in read
    name=name)
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\tensorflow\python\ops\gen_data_flow_ops.py", line 1997, in _tensor_array_read_v3
    name=name)
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\tensorflow\python\framework\ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\tensorflow\python\framework\ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): TensorArray map_2/TensorArray_1_22: Could not read from TensorArray index 1 because it has not yet been written to.
	 [[Node: map_2/while/TensorArrayReadV3_1 = TensorArrayReadV3[dtype=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](map_2/while/TensorArrayReadV3_1/Enter, map_2/while/Identity, map_2/while/TensorArrayReadV3_1/Enter_1)]]
