In [1]:
import tensorflow as tf

import numpy as np

import pylab as pl
%pylab inline

import pandas as pd
from pandas import Series, DataFrame

Populating the interactive namespace from numpy and matplotlib


In [2]:
import scipy.sparse as scsp

In [3]:
x = tf.Variable(2.0, name = "x", dtype=tf.float32 )

In [4]:
v = tf.Variable([1.0, 3, 4])

In [5]:
M = tf.SparseTensor(
    indices=[[0, 0], [1, 2]], 
    values=[1.0, 2], 
    dense_shape=[3, 4]
)

In [37]:
tf.reshape(v, [3, 1]) * M

In [19]:
A = tf.Variable(np.diag([1, 2, 3]), name = "A", dtype = tf.float32)

In [20]:
tf.reshape(v, [3, 1]) * A

<tf.Tensor 'mul_5:0' shape=(3, 3) dtype=float32>

In [34]:
M2 = tf.SparseTensor(
    indices=[ [1, 2], [0, 0], [0,0]], 
    values=v, 
    dense_shape=[3, 4]
)

In [35]:
init = tf.global_variables_initializer()

In [40]:
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(tf.sparse_reorder(M2), feed_dict={v: [4, 5, 6]}))
    val = sess.run(tf.reshape(v, [3, 1]) * M2 , feed_dict={v: [4, 5, 6]})
    print(val)

SparseTensorValue(indices=array([[0, 0],
       [0, 0],
       [1, 2]], dtype=int64), values=array([ 5.,  6.,  4.], dtype=float32), dense_shape=array([3, 4], dtype=int64))
SparseTensorValue(indices=array([[1, 2],
       [0, 0],
       [0, 0]], dtype=int64), values=array([ 20.,  20.,  24.], dtype=float32), dense_shape=array([3, 4], dtype=int64))


In [44]:
tf.sparse_to_dense(val.indices, val.dense_shape, val.values)

<tf.Tensor 'SparseToDense_4:0' shape=(3, 4) dtype=float32>

In [ ]:
def tf_SparseTensorValue_to_dense_np(t):
    t1 = np.zeros(t.dense_shape)
    for ii, val in zip(t.indices, t.values):
        t1[tuple(ii)] += val
        
    return t1
    

In [11]:
tf_SparseTensorValue_to_dense_np(val)

NameError: name 'val' is not defined

In [53]:
vc = tf.reshape(v, [3, 1]) 

In [57]:
vc * M

In [56]:
M

## operations between sparse and dense

In [8]:
a = tf.SparseTensor(
    indices = [[0], [3], [6], [9]], 
    values = [1, 1, 1, 1], 
    dense_shape=[10],
)

In [9]:
b = tf.Variable(np.arange(10))

In [10]:
sess = tf.InteractiveSession()
sess.run(tf.global_variables_initializer())

In [12]:
tf_SparseTensorValue_to_dense_np(
    sess.run(a)
)

array([ 1.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  1.])

In [14]:
sess.run(a * b)

SparseTensorValue(indices=array([[0],
       [3],
       [6],
       [9]], dtype=int64), values=array([0, 3, 6, 9]), dense_shape=array([10], dtype=int64))

In [16]:
sess.run(a[:, None] * b[None, :])

TypeError: 'SparseTensor' object is not subscriptable

In [23]:
sess.run(tf.sparse_reshape(a, [tf.shape(a)[0], 1]) * b[None, :])

InvalidArgumentError: SparseDenseBinaryOpShared broadcasts dense to sparse only; got incompatible shapes: [10,1] vs. [1,10]
	 [[Node: mul_2 = SparseDenseCwiseMul[T=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](SparseReshape_2, SparseReshape_2/Identity, SparseReshape_2:1, strided_slice_4)]]

Caused by op 'mul_2', defined at:
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\ipykernel\__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\ipykernel\kernelapp.py", line 474, in start
    ioloop.IOLoop.instance().start()
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\zmq\eventloop\ioloop.py", line 162, in start
    super(ZMQIOLoop, self).start()
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\tornado\ioloop.py", line 887, in start
    handler_func(fd_obj, events)
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\tornado\stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\zmq\eventloop\zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\zmq\eventloop\zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\zmq\eventloop\zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\tornado\stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\ipykernel\kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\ipykernel\kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\ipykernel\kernelbase.py", line 390, in execute_request
    user_expressions, allow_stdin)
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\ipykernel\ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\ipykernel\zmqshell.py", line 501, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\IPython\core\interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\IPython\core\interactiveshell.py", line 2827, in run_ast_nodes
    if self.run_code(code, result):
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-23-c380efb30fc0>", line 1, in <module>
    sess.run(tf.sparse_reshape(a, [tf.shape(a)[0], 1]) * b[None, :])
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\tensorflow\python\ops\math_ops.py", line 849, in binary_op_wrapper_sparse
    name=name), sp_x.dense_shape)
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\tensorflow\python\ops\gen_sparse_ops.py", line 603, in sparse_dense_cwise_mul
    dense=dense, name=name)
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\tensorflow\python\framework\ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Users\sakalos\moje\python\WinPython\WinPython-64bit-3.5.2.3\python-3.5.2.amd64\lib\site-packages\tensorflow\python\framework\ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): SparseDenseBinaryOpShared broadcasts dense to sparse only; got incompatible shapes: [10,1] vs. [1,10]
	 [[Node: mul_2 = SparseDenseCwiseMul[T=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](SparseReshape_2, SparseReshape_2/Identity, SparseReshape_2:1, strided_slice_4)]]


In [22]:
tf.sparse_reshape(a, [a.dense_shape[0], 1])

In [24]:
tf.tile(a, 10)

TypeError: Failed to convert object of type <class 'tensorflow.python.framework.sparse_tensor.SparseTensor'> to Tensor. Contents: SparseTensor(indices=Tensor("SparseTensor_2/indices:0", shape=(4, 1), dtype=int64), values=Tensor("SparseTensor_2/values:0", shape=(4,), dtype=int32), dense_shape=Tensor("SparseTensor_2/dense_shape:0", shape=(1,), dtype=int64)). Consider casting elements to a supported type.

# Sparse tensor feeding

In [14]:
import tensorflow as tf
import numpy as np

##### The natural way does not work:

In [12]:
a = tf.SparseTensor(
    indices = [[0, 0], [3, 3], [6, 6], [9, 9]], 
    values = [1, 1, 1, 1], 
    dense_shape=[10, 10],
)

In [16]:
v = tf.Variable(np.arange(10))

In [17]:
w = tf.sparse_tensor_dense_matmul(a, v[:, None])[:, 0]

In [18]:
sess = tf.InteractiveSession()
sess.run(tf.global_variables_initializer())

In [20]:
sess.run([a, w])

[SparseTensorValue(indices=array([[0, 0],
       [3, 3],
       [6, 6],
       [9, 9]], dtype=int64), values=array([1, 1, 1, 1]), dense_shape=array([10, 10], dtype=int64)),
 array([0, 0, 0, 3, 0, 0, 6, 0, 0, 9])]

In [24]:
a_val = tf.SparseTensorValue(
    indices = [[0, 0], [3, 3], [6, 6], [9, 9]], 
    values = [2, 2, 2, 2], 
    dense_shape=np.array([10, 10], dtype=np.int32),
)

In [25]:
sess.run([a, w], feed_dict={a: a_val})

ValueError: Tensor Tensor("SparseTensor_3/dense_shape:0", shape=(2,), dtype=int64) may not be fed.

##### We must use a workaround:

In [51]:
tf.reset_default_graph()

In [52]:
a2_indices = tf.Variable( [[0, 0], [3, 3], [6, 6], [9, 9]], validate_shape= False, dtype=np.int64)
a2_indices.set_shape([None, 2])

In [53]:
a2_shape = tf.Variable([10, 10], dtype=np.int64)

In [54]:
a2_values = tf.Variable( [1, 1, 1, 1], validate_shape= False, dtype=np.int32)
a2_values.set_shape([None])

In [55]:
a2 = tf.SparseTensor(
    indices = a2_indices,
    values = a2_values, 
    dense_shape=a2_shape,
)

In [67]:
v2 = tf.Variable(np.arange(10), validate_shape= False, dtype=np.int32)
v2.set_shape([None])

In [68]:
w2 = tf.sparse_tensor_dense_matmul(a2, v2[:, None])[:, 0]

In [69]:
sess = tf.InteractiveSession()
sess.run(tf.global_variables_initializer())

In [70]:
sess.run(w2)

array([0, 0, 0, 3, 0, 0, 6, 0, 0, 9])

In [71]:
sess.run([a2, w2])

[SparseTensorValue(indices=array([[0, 0],
       [3, 3],
       [6, 6],
       [9, 9]], dtype=int64), values=array([1, 1, 1, 1]), dense_shape=array([10, 10], dtype=int64)),
 array([0, 0, 0, 3, 0, 0, 6, 0, 0, 9])]

In [72]:
sess.run([a2, w2], 
    feed_dict={
        a2_indices: [[1, 1], [3, 3]],
        a2_values: [2, 2],
    }
)

[SparseTensorValue(indices=array([[1, 1],
       [3, 3]], dtype=int64), values=array([2, 2]), dense_shape=array([10, 10], dtype=int64)),
 array([0, 2, 0, 6, 0, 0, 0, 0, 0, 0])]

In [73]:
sess.run([a2, w2], 
    feed_dict={
        a2_indices: [[1, 1], [3, 3]],
        a2_values: [2, 2],
        a2_shape: [5, 5],
        v2: np.arange(5)
    }
)

[SparseTensorValue(indices=array([[1, 1],
       [3, 3]], dtype=int64), values=array([2, 2]), dense_shape=array([5, 5], dtype=int64)),
 array([0, 2, 0, 6, 0])]

##### bundle into a nice class

In [74]:
import sys
sys.path.append(r"..\Commons")

import ptf_02 as ptf

In [75]:
a3 = ptf.SparseMatrix(
    indices = [[0, 0], [3, 3], [6, 6], [9, 9]], 
    values = [1, 1, 1, 1], 
    dense_shape=[10, 10],
)

In [76]:
w3 = tf.sparse_tensor_dense_matmul(a3.tensor, v2[:, None])[:, 0]

In [77]:
sess.run(tf.global_variables_initializer())

In [78]:
sess.run([a3.tensor, w3])

[SparseTensorValue(indices=array([[0, 0],
       [3, 3],
       [6, 6],
       [9, 9]], dtype=int64), values=array([1, 1, 1, 1]), dense_shape=array([10, 10], dtype=int64)),
 array([0, 0, 0, 3, 0, 0, 6, 0, 0, 9])]

In [79]:
sess.run([a3.tensor, w3], 
    feed_dict={
        a3.indices: [[1, 1], [3, 3]],
        a3.values: [2, 2],
        a3.dense_shape: [5, 5],
        v2: np.arange(5)
    }
)

[SparseTensorValue(indices=array([[1, 1],
       [3, 3]], dtype=int64), values=array([2, 2]), dense_shape=array([5, 5], dtype=int64)),
 array([0, 2, 0, 6, 0])]