In [1]:
import tensorflow as tf

In [2]:
# Import TensorFlow eager execution support (subject to future changes).
import tensorflow.contrib.eager as tfe

tfe.enable_eager_execution()

In [9]:
import numpy.random as rnd

In [4]:
x = tf.get_variable(
    name = "x", 
    shape = [2, 3], 
    dtype = tf.float32,
    initializer = tf.zeros_initializer
)

In [5]:
x

<tf.Variable 'x:0' shape=(2, 3) dtype=float32, numpy=
array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]], dtype=float32)>

In [6]:
x.numpy()

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]], dtype=float32)

In [13]:
x.assign(rnd.rand(2, 3));

In [14]:
x.numpy()

array([[ 0.55364311,  0.56231737,  0.61521262],
       [ 0.08251356,  0.65010899,  0.03129011]], dtype=float32)