In [87]:
import numpy as np
import numpy.linalg as la
import tensorflow as tf

In [88]:
## choose our matrix
A = np.array([
        [ 10, -10],
        [-45, -41],
    ],
    dtype = np.float32      
)

In [89]:
## a method for checking the SVD of A
def check_USV(U, S, V):
    S_diag = S * np.eye(*A.shape)
    reconstruction = U @  np.diag(S) @ V
    print( reconstruction )
    print("error =", np.max(np.abs(A - reconstruction)))

In [90]:
#############
## Numpy SVD

U, S, V = la.svd(A)
check_USV(U, S, V)

[[ 10. -10.]
 [-45. -41.]]
error = 0.0


In [91]:
############
## Tensorflow SVD

## tensorflow.svd has different ordering of outputs 
s, u, v = tf.svd(tf.constant(A), full_matrices=True)

with tf.Session() as sess:
    U_tf, S_tf, V_tf =  sess.run([u, s, v])

check_USV(U_tf, S_tf, V_tf)

[[ -8.97085476 -10.93269444]
 [-45.21641159  40.76120758]]
error = 81.7612


In [93]:
print(V)
print(V_tf)

[[-0.74097639 -0.67153108]
 [ 0.67153108 -0.74097639]]
[[ 0.74097639 -0.67153108]
 [ 0.67153108  0.74097639]]


In [95]:
print(U)
print(U_tf)

[[-0.01140679  0.99993491]
 [ 0.99993491  0.01140679]]
[[ 0.01140678 -0.99993497]
 [-0.99993497 -0.01140678]]


In [97]:
U_tf @  np.diag(S_tf) @ V_tf.T

array([[ 10.00000095, -10.00000095],
       [-45.00000381, -41.        ]], dtype=float32)