In [46]:
import numpy as np
import numpy.linalg as la
import tensorflow as tf

In [71]:
## choose our matrix
A = np.array([
        [ 10, -10],
        [-45, -41],
        [ 0  , 0  ],
    ],
    dtype = np.float32      
)


In [72]:
## a method for checking the SVD of A
def check_USV(U, S, V):
    S_diag = S * np.eye(*A.shape)
    reconstruction = U @  S_diag @ V
    print( reconstruction )
    print("error =", np.max(np.abs(A - reconstruction)))

In [73]:
#############
## Numpy SVD

U, S, V = la.svd(A)
check_USV(U, S, V)

[[  9.99999958  -9.99999993]
 [-44.99999961 -40.99999793]
 [  0.           0.        ]]
error = 2.06837245287e-06


In [74]:
############
## Tensorflow SVD

## tensorflow.svd has different ordering of outputs 
s, u, v = tf.svd(tf.constant(A), full_matrices=True)

with tf.Session() as sess:
    U_tf, S_tf, V_tf =  sess.run([u, s, v])

check_USV(U_tf, S_tf, V_tf)

[[ -8.97084741 -10.93269697]
 [-45.21641503  40.76121307]
 [  0.           0.        ]]
error = 81.7612130656


In [70]:
print(U)
print(U_tf)

[[-1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[ -1.00000024e+00   5.96046448e-08   0.00000000e+00]
 [  0.00000000e+00  -1.00000012e+00   0.00000000e+00]
 [  0.00000000e+00  -0.00000000e+00   1.00000000e+00]]


In [75]:
print(V)
print(V_tf)

[[-0.74097639 -0.67153108]
 [ 0.67153108 -0.74097639]]
[[ 0.74097639 -0.67153108]
 [ 0.67153108  0.74097639]]


In [77]:
print(tf.GIT_VERSION, tf.VERSION)

b'unknown' 1.2.0
