In [3]:
import numpy as np
import numpy.linalg as la
import tensorflow as tf

In [11]:
## choose our matrix
A = np.array([
        [ 0.13006589, -0.12793152],
        [-0.04599907, -0.04176966],
        [ 0.        , -0.        ],
    ])


In [25]:
## a method for checking the SVD of A
def check_USV(U, S, V):
    S_diag = S * np.eye(*A.shape)
    reconstruction = U @  S_diag @ V
    print( reconstruction )
    print("error =", np.max(np.abs(A - reconstruction)))

In [26]:
#############
## Numpy SVD

U, S, V = la.svd(A)
check_USV(U, S, V)

[[ 0.13006589 -0.12793152]
 [-0.04599907 -0.04176966]
 [ 0.          0.        ]]
error = 8.32667268469e-17


In [33]:
############
## Tensorflow SVD

## tensorflow.svd has different ordering of outputs 
s, u, v = tf.svd(tf.constant(A), full_matrices=True)

with tf.Session() as sess:
    U_tf, S_tf, V_tf =  sess.run([u, s, v])

check_USV(U_tf, S_tf, V_tf)

[[ 0.13194017  0.12599762]
 [ 0.04030932 -0.04728401]
 [ 0.          0.        ]]
error = 0.253929142182


In [31]:
print(U)
print(U_tf)

[[-0.99976429  0.02171097  0.        ]
 [ 0.02171097  0.99976429  0.        ]
 [ 0.          0.          1.        ]]
[[ 0.99976429 -0.02171097  0.        ]
 [-0.02171097 -0.99976429  0.        ]
 [ 0.         -0.          1.        ]]


In [32]:
print(V)
print(V_tf)

[[-0.71808849  0.69595181]
 [-0.69595181 -0.71808849]]
[[ 0.71808849  0.69595181]
 [-0.69595181  0.71808849]]
