In [1]:
import numpy as np
import h5py

In [59]:
file_path = "../tmp/aaa.h5"
f = h5py.File(file_path)

In [4]:
dataset = f.create_dataset("data", data = np.arange(20).reshape([4, 5]))
# alternatively
f["data2"] = np.zeros(10)

In [14]:
print("name:", dataset.name)
print("group:", dataset.parent)

name: /data
group: <HDF5 group "/" (1 members)>


In [16]:
f.keys()

hdf_keys(['data', 'data2'])

In [19]:
f["group1/aa"] = [1, 0, 1]
# equivalent:
f["group1"]["bb"] = [2,  0, 2]

In [21]:
f.keys()

hdf_keys(['data', 'data2', 'group1'])

#### Attributes

In [29]:
dataset = f["data"]
dataset.attrs["description"] = "This is a dataset."
dict(dataset.attrs)

{'description': 'This is a dataset.'}

In [30]:
group = f["group1"]
group.attrs["description"] = "This is a group."
dict(group.attrs)

{'description': 'This is a group.'}

In [32]:
np.array(dataset)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [37]:
dataset.dims[0].label = "x"
dataset.dims[1].label = "y"

In [38]:
dataset

<HDF5 dataset "data": shape (4, 5), type "<i4">

**Deleting**

In [60]:
f.keys()

hdf_keys(['data', 'data2', 'data3', 'data4', 'group1'])

In [61]:
del(f["data"])

In [62]:
f.keys()

hdf_keys(['data2', 'data3', 'data4', 'group1'])

In [63]:
f.close()

### Append to existing dataset

In [64]:
g = h5py.File(file_path)

Try to append to one of the datasets we defined above

In [46]:
dset = g["data2"]
dset[:]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [47]:
dset.shape

(10,)

In [48]:
# to add 5 more elements we need first resize the dataset
dset.resize([dset.shape[0] + 5])
dset

TypeError: Only chunked datasets can be resized

OK, define chunked dataset

In [ ]:
dset = g.create_dataset(
    name="data3", shape=[0], chunks=True, dtype=np.float32)

In [52]:
dset[...]

array([], dtype=float32)

In [54]:
# to add 5 more elements we need first resize the dataset
dset.resize([dset.shape[0] + 5])
dset

ValueError: Unable to set extend dataset (dimension cannot exceed the existing maximal size (new: 5 max: 0))

Ok, specify maximal size

In [55]:
dset = g.create_dataset(
    name="data4", shape=[0], chunks=True, dtype=np.float32, maxshape = (None,))

In [56]:
# to add 5 more elements we need first resize the dataset
dset.resize([dset.shape[0] + 5])
dset

<HDF5 dataset "data4": shape (5,), type "<f4">

In [57]:
dset[...]

array([0., 0., 0., 0., 0.], dtype=float32)

In [58]:
g.close()