In [1]:
import tensorflow as tf
import tensorflow_probability as tfp
import numpy as np

In [2]:
tf.__version__

'2.1.0'

In [3]:
tfp.__version__

'0.9.0'

In [18]:
minimum = np.array([1.0, 1.0])  # The center of the quadratic bowl.
scales = np.array([2.0, 3.0])  # The scales along the two axes.

# The objective function and the gradient.
def quadratic_loss_and_gradient(x):
    return tfp.math.value_and_gradient(
        lambda x: tf.reduce_sum(scales * tf.math.squared_difference(x, minimum), axis=-1), x)

start = tf.constant([0.6, 0.8])  # Starting point for the search.
optim_results = tfp.optimizer.bfgs_minimize(
  quadratic_loss_and_gradient, initial_position=start, tolerance=1e-8)

# Check that the search converged
assert(optim_results.converged)
# Check that the argmin is close to the actual value.
np.testing.assert_allclose(optim_results.position, minimum)
# Print out the total number of function evaluations it took. Should be 5.
print ("Function evaluations: %d" % optim_results.num_objective_evaluations)
print("Minimum position:", optim_results.position.numpy() )

Function evaluations: 5
Minimum position: [1. 1.]


In [22]:
minimum = np.array([[1.0, 1.0], [1., 2.], [2., 2.]])  # The center of the quadratic bowl.
scales = np.array([[2.0, 3.0]])  # The scales along the two axes.

# The objective function and the gradient.
def quadratic_loss_and_gradient(x):
    return tfp.math.value_and_gradient(
        lambda x: tf.reduce_sum(scales * tf.math.squared_difference(x, minimum), axis=-1), x)

start = tf.zeros_like(minimum)  # Starting point for the search.
optim_results = tfp.optimizer.bfgs_minimize(
  quadratic_loss_and_gradient, initial_position=start, tolerance=1e-8)

# Check that the search converged
print("converged:", optim_results.converged)
# Check that the argmin is close to the actual value.
np.testing.assert_allclose(optim_results.position, minimum)
# Print out the total number of function evaluations it took.
print("Function evaluations: %d" % optim_results.num_objective_evaluations)
print("Minimum position:", optim_results.position.numpy() )

converged: tf.Tensor([ True  True  True], shape=(3,), dtype=bool)
Function evaluations: 5
Minimum position: [[1. 1.]
 [1. 2.]
 [2. 2.]]


In [15]:
optim_results.position.

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[1., 1.]], dtype=float32)>

In [13]:
quadratic_loss_and_gradient(start)

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.43999994], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([-1.5999999, -1.1999999], dtype=float32)>)

In [ ]:
tfp.math.value_and_gradient()

In [10]:
x = tf.Variable(0.)

In [11]:
with tf.GradientTape() as tape:
    y = x**2

In [ ]:
tape.gradient()